package Exception_Class;

    public class Use_Of_Throw {
	public static void main(String[] args) {
		
	System.out.println("HI");
	
	throw new ArithmeticException();
	
	}
    }
 